name: JavaMicroservice
home: https://kubernauts.io/
icon: https://jenkins.io/images/logos/jenkins/jenkins.png
version: 0.0.1
appVersion: 2.140
description: Java application example
keywords:
- continuous-delivery
- continuous-deployment
- continuous-integration
- docker
- java
sources:
- https://github.com/muellermh/rancher-chart
maintainers:
- name: Manuel Müller
  email: mm@kubernauts.de
