
image:
  repository: https://hub.docker.com/muellermh/example
  tag: latest
  pullPolicy: IfNotPresent

service:
  httpPort: 8080
  type: LoadBalancer

ingress:
  enabled: false

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

helloWorld: "bitte nicht ändern :)"